name: Contributions

on:
  workflow_dispatch: # Execute manually
  schedule: # Execute every 23 hours
    - cron: "0 23 * * *"

jobs:
          
  snake-animation:
    runs-on: ubuntu-latest
    steps:
      - name: Contributions
        uses: Platane/snk@main
        id: snake-gif
        with:
          github_user_name:  ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish Snake Animation SVG
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: contributions
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
